name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
